#! /bin/bash
#
# This script serves as a wrapper around the openrc configuration script.  
# The latter is expected to be generated by the OpenStack dashboard and is
# specific to the user.  This wrapper customized the environment for further 
# use with NDS Labs on nebula.  
#
# Copy this file to the same directory as the [project]-openrc.sh script.
# Edit as necessary.
#
export OS_PROJECT_NAME="NDSLabs"
export USER_OPENRC="${OS_PROJECT_NAME}-openrc.sh"

source $USER_OPENRC

expr match "$OS_AUTH_URL" "http://nebula.ncsa.illinois.edu/" > /dev/null && {
    export NOVA_VOLUME_SERVICE_NAME=cinder
}
